import Cachorrinho from '../assets/img/Chorrinho1.jpg';
import channel1 from '../assets/img/Channel.jpg';

const videosDogs = [
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
  {
    src: Cachorrinho,
    alt: 'Bem vindos a CuteFlix!',
    title: 'CuteFlix',
    avatar: channel1,
    channelName: 'Bem vindos a CuteFlix!',
    timer: '00:00',
    link: 'Cachorrinho',
  },
];

export default videosDogs;
